# Generated by Django 4.2.4 on 2023-08-29 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_line', models.CharField(choices=[('Ferreteria', 'Ferreteria'), ('Almacen', 'Almacen'), ('Otros', 'Otros')], default='Otros', max_length=128)),
                ('qt', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('code', models.CharField(max_length=32)),
                ('expiration', models.DateField(default=None, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('client', 'code')},
            },
        ),
    ]
