# Generated by Django 4.2.4 on 2023-08-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_stockmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmodel',
            name='image',
            field=models.FileField(default=None, null=True, upload_to='images/'),
        ),
    ]
