# Generated by Django 4.2.4 on 2023-09-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_stockmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmodel',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
