# Generated by Django 4.2.4 on 2023-09-07 00:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_stockmodel_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartmodel',
            unique_together={('client', 'stock')},
        ),
    ]
